[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mscales"
version = "1.4.1"
description = "A Python package to generate, visualize, and sonify musical scales."
readme = "README.md"
authors = [{name = "Fabian C. Moss", email = "fabianmoss@gmail.com"}]
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.4",
    "pretty_midi>=0.2.10",
    "matplotlib>=3.8.4",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "C4", "SIM"]
ignore = ["UP038"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"mscales/tests/*" = ["F401"]

[tool.pytest.ini_options]
testpaths = ["mscales/tests"]
